steps:
  # Build the container image using Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/playground-neural:$COMMIT_SHA'
      - '.'
      - '--build-arg'
      - 'NODE_ENV=production'
      - '--build-arg'
      - 'NEXT_TELEMETRY_DISABLED=1'
    dir: 'frontend'
    env:
      - 'NODE_ENV=production'
      - 'NEXT_TELEMETRY_DISABLED=1'
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/playground-neural:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'playground-neural'
      - '--image'
      - 'gcr.io/$PROJECT_ID/playground-neural:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
      - '--memory'
      - '4Gi'
      - '--cpu'
      - '4'
      - '--max-instances'
      - '20'
      - '--min-instances'
      - '1'
      - '--concurrency'
      - '1000'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'NODE_ENV=production,NEXT_TELEMETRY_DISABLED=1,NEXT_PUBLIC_API_URL=https://playgroundai-backend-uaaur7no2a-uc.a.run.app'

images:
  - 'gcr.io/$PROJECT_ID/playground-neural:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
